#!/usr/bin/env bash

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

# Get the hostname
hostname=$(hostname)

# Define custom header configuration
custom_header="add_header X-Served-By $hostname;"

# Add the custom header to the default Nginx configuration file
sudo sed -i "/http {/a \ \ \ \ $custom_header" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo service nginx restart
