#!/usr/bin/env bash
# Installing Nginx with the specified configuration

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html >/dev/null
sudo touch /var/www/html/404.html
echo "can not upload the page :<" | sudo tee /var/www/html/404.html >/dev/null

sudo printf '%s' 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://google.com/;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}' | sudo tee /etc/nginx/sites-available/default >/dev/null

sudo service nginx restart
