#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100
num=1
while ((num < 101))
do
    if [ $((num % 3)) -eq 0 ] && [ $((num % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((num % 3)) -eq 0 ]
    then 
        echo "Fizz"
    elif [ $((num % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$num"
    fi
    ((num++))
done
