#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with while with hi
i=1
while ((i < 11))
do
    echo "Best School"
    if ((i == 9))
    then
        echo "Hi"
    fi
    ((i++))
done
